before_install: npm install mocha
language: node_js
node_js:
- '6.0'
install: npm install
deploy:
  provider: s3
  access_key_id: "${AWS_ACCESS_KEY}"
  bucket: "devopsaws.com"
  secret_access_key: "${AWS_SECRET_KEY}"
  region: us-west-2

